package model;

import exceptions.DogException;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Todo extends Task {
    public Todo(String description) {
        super(description);
    }

    public Todo(String description, boolean isDone) {
        super(description, isDone);
    }

    @Override
    public String toSaveFormat() {
        return String.format("T | %s | %s", getStatusIcon(), description);
    }

    /**
     * Parses a task from its saved string format.
     * 
     * @param saveString the saved string in format "T | [X or space] | description"
     * @return the parsed Todo, or null if the format is invalid
     */
    public static Todo fromSaveFormat(String saveString) {
        if (saveString == null) return null;

        String[] parts = saveString.split(" \\| ", 3);
        if (parts.length < 3) return null;

        String taskIcon = parts[0];
        String statusIcon = parts[1];
        String description = parts[2];

        // Return null if task/status icon is invalid
        if (!taskIcon.equals("T") || !statusIcon.equals("X") && !statusIcon.equals(" ")) {
            return null;
        }

        boolean isDone = statusIcon.equals("X");

        return new Todo(description, isDone);
    }

    public static Todo parse(String input) throws DogException {
        String BAD_INPUT_MSG = "ToDo tasks must have a description!\n"
                + "Expected: todo <description>";

        // Code generated by Codex with Qwen3-coder-next
        // Pattern: " <description>"
        Pattern pattern = Pattern.compile("^\\s+(.+?)\\s*$");
        Matcher matcher = pattern.matcher(input);

        if (!matcher.matches()) {
            throw new DogException(BAD_INPUT_MSG);
        }

        String description = matcher.group(1).trim();

        if (description.isEmpty()) {
            throw new DogException(BAD_INPUT_MSG);
        }

        return new Todo(description);
    }

    @Override
    public String toString() {
        return "[T]" + super.toString();
    }
}
