import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Deadline extends Task {
    protected String by;

    public Deadline(String description, String by) {
        super(description);
        this.by = by;
    }

    public Deadline(String description, String by, boolean isDone) {
        super(description, isDone);
        this.by = by;
    }

    @Override
    public String toSaveFormat() {
        return String.format("D | %s | %s | %s", getStatusIcon(), by, description);
    }

    public static Deadline fromSaveFormat(String saveString) {
        String[] parts = saveString.split(" \\| ", 4);
        if (parts.length < 4) return null;

        String statusIcon = parts[1].trim();
        String by = parts[2].trim();
        String description = parts[3].trim();
        boolean isDone = statusIcon.equals("X");

        return new Deadline(description, by, isDone);
    }

    public static Deadline parse(String input) throws DogException {
        String BAD_INPUT_MSG = "Deadline tasks must have a description and deadline!\n"
                + "Expected: deadline <description> /by <deadline>";

        // Code generated by Codex with Qwen3-coder-next
        // Pattern: " <description> /by <by>"
        Pattern pattern = Pattern.compile("^\\s+(.+?)\\s+/by\\s+(.+?)\\s*$");
        Matcher matcher = pattern.matcher(input);

        if (!matcher.matches()) {
            throw new DogException(BAD_INPUT_MSG);
        }

        String description = matcher.group(1).trim();
        String by = matcher.group(2).trim();

        if (description.isEmpty() || by.isEmpty()) {
            throw new DogException(BAD_INPUT_MSG);
        }

        return new Deadline(description, by);
    }

    @Override
    public String toString() {
        return "[D]" + super.toString() + " (by: " + this.by + ")";
    }
}
