import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Deadline extends Task {
    protected String by;

    public Deadline(String description, String by) {
        super(description);
        this.by = by;
    }

    public static Deadline parse(String input) throws DogException {
        // Code generated by Codex with Qwen3-coder-next
        // Pattern: " <description> /by <by>"
        Pattern pattern = Pattern.compile("^\\s+(.+?)\\s+/by\\s+(.+?)\\s*$");
        Matcher matcher = pattern.matcher(input);

        if (!matcher.matches()) {
            throw new DogException("Deadline tasks must have a description and deadline!\n" +
                    "Expected: deadline <description> /by <deadline>");
        }

        String description = matcher.group(1).trim();
        String by = matcher.group(2).trim();

        if (description.isEmpty() || by.isEmpty()) {
            throw new DogException("Deadline tasks can't have an empty description or deadline!");
        }

        return new Deadline(description, by);
    }

    @Override
    public String toString() {
        return "[D]" + super.toString() + " (by: " + this.by + ")";
    }
}
