import java.util.Scanner;

public class Dog {
    private static final Storage storage = new Storage("./data/dog.txt");
    private static final Ui ui = new Ui();
    private static TaskList taskList = new TaskList();

    // enum Code generated by Codex with Qwen3-coder-next with some modifications
    private enum Command {
        LIST,
        MARK,
        DELETE,
        TODO,
        DEADLINE,
        EVENT,
        BYE;

        public static Command fromInput(String input) {
            String lowerInput = input.toLowerCase().trim();
            for (Command cmd : Command.values()) {
                if (cmd.name().toLowerCase().equals(lowerInput)) {
                    return cmd;
                }
                if (lowerInput.startsWith(cmd.name().toLowerCase())) {
                    return cmd;
                }
            }
            return null;
        }

        public String getCommandRest(String input) {
            if (!input.startsWith(this.name().toLowerCase())) {
                return "";
            }
            return input.substring(this.name().length());
        }
    }

    public static void main(String[] args) {
        ui.showWelcome();
        taskList = new TaskList(storage.load());
        Scanner scanner = new Scanner(System.in);

        while (scanner.hasNextLine()) {
            try {
                String input = scanner.nextLine().trim();
                if (input.isEmpty()) {
                    ui.askForInput();
                } else {
                    Command command = Command.fromInput(input);
                    if (command == null) {
                        throw new DogException("I don't understand what you're saying :(");
                    }

                    String rest = command.getCommandRest(input);

                    switch (command) {
                        case BYE:
                            storage.save(taskList.getTasks());
                            ui.showGoodbye();
                            scanner.close();
                            return;
                        case LIST:
                            ui.showMessage("Here are the tasks in your list:");
                            ui.showTaskList(taskList.getTasks());
                            break;
                        case MARK:
                            try {
                                int index = Integer.parseInt(rest.trim()) - 1;
                                if (index >= 0 && index < taskList.size()) {
                                    taskList.markTask(index);
                                    ui.showTaskMarked(taskList.getTask(index));
                                } else {
                                    throw new DogException("Task index out of bounds.");
                                }
                            } catch (NumberFormatException e) {
                                throw new DogException("Please provide a valid task number. (e.g., 'mark 2').");
                            }
                            storage.save(taskList.getTasks());
                            break;
                        case DELETE:
                            try {
                                int index = Integer.parseInt(rest.trim()) - 1;
                                if (index >= 0 && index < taskList.size()) {
                                    Task deletedTask = taskList.deleteTask(index);
                                    ui.showTaskDeleted(deletedTask, taskList.size());
                                } else {
                                    throw new DogException("Task index out of bounds.");
                                }
                            } catch (NumberFormatException e) {
                                throw new DogException("Please provide a valid task number. (e.g., 'delete 2').");
                            }
                            storage.save(taskList.getTasks());
                            break;
                        case TODO:
                            Task newTodo = Todo.parse(rest);
                            taskList.addTask(newTodo);
                            ui.showTaskAdded(newTodo);
                            storage.save(taskList.getTasks());
                            break;
                        case DEADLINE:
                            Task newDeadline = Deadline.parse(rest);
                            taskList.addTask(newDeadline);
                            ui.showTaskAdded(newDeadline);
                            storage.save(taskList.getTasks());
                            break;
                        case EVENT:
                            Task newEvent = Event.parse(rest);
                            taskList.addTask(newEvent);
                            ui.showTaskAdded(newEvent);
                            storage.save(taskList.getTasks());
                            break;
                    }
                }
            } catch (DogException e) {
                ui.showError(e.getMessage());
            } finally {
                ui.showLine();
            }
        }
    }
}