import java.util.ArrayList;
import java.util.Scanner;

public class Dog {
    private static ArrayList<Task> taskList = new ArrayList<Task>();

    /**
     * Displays the current tasks in the list.
     */
    private static void displayTaskList() {
        if (taskList.isEmpty()) {
            System.out.println(" (Your list is currently empty)");
        } else {
            for (int i = 0; i < taskList.size(); i++) {
                System.out.println((i + 1) + ". " + taskList.get(i));
            }
        }
    }

    public static void main(String[] args) {
        String line = "____________________________________________________________";
        String banner = "      _____                \n"
                + "      |  __ \\  ____   ___ _ \n"
                + "      | |  | |/ __ \\ / __' |\n"
                + "      | |  | | |  | | |__| |\n"
                + "      | |__| | |__| |\\___  |\n"
                + "      |_____/ \\____/ ____/ |\n"
                + "                     \\____/ \n";
        String greeting = "WOOF WOOF How can I help? WOOF";

        System.out.println(banner);
        System.out.println(greeting);
        System.out.println(line);
        System.out.println("\n");
        
        Scanner scanner = new Scanner(System.in);
        while (scanner.hasNextLine()) {
            String input = scanner.nextLine().trim();
            if (input.isEmpty()) continue;

            System.out.println(line);

            if (input.equalsIgnoreCase("bye")) {
                // Say goodbye and exit
                System.out.println("WOOF Goodbye! WOOF WOOF");
                System.out.println(line);
                break;
            } else if (input.equalsIgnoreCase("list")) {
                // Print list of tasks
                System.out.println("Here are the tasks in your list:");
                displayTaskList();
                System.out.println(line);
                System.out.println("\n");
            } else if (input.toLowerCase().startsWith("mark ")) {
                // Handle marking a task as done: "mark <index>"
                // Code generated by Codex with Gemma4 26b
                try {
                    int index = Integer.parseInt(input.substring(5).trim()) - 1;
                    if (index >= 0 && index < taskList.size()) {
                        Task taskToMark = taskList.get(index);
                        taskToMark.markAsDone();
                        System.out.println("     WOOF! I've marked this task as done:");
                        System.out.println("       " + taskToMark);
                        System.out.println(line);
                        System.out.println("\n");
                    } else {
                        System.out.println("     Error: Task index out of bounds.");
                        System.out.println(line);
                        System.out.println("\n");
                    }
                } catch (NumberFormatException e) {
                    System.out.println("     Error: Please provide a valid task number (e.g., 'mark 2').");
                    System.out.println(line);
                    System.out.println("\n");
                }
            } else {
                // Add task to list if the input is just a description
                Task newTask = new Task(input);
                taskList.add(newTask);
                System.out.println("WOOF! I've added a new task: \n" + newTask);
                System.out.println(line);
                System.out.println("\n");
            }
        }
    }
}