import java.util.ArrayList;
import java.util.Scanner;

public class Dog {
    private static ArrayList<Task> taskList = new ArrayList<Task>();

    /**
     * Displays the current tasks in the list.
     */
    private static void displayTaskList() {
        if (taskList.isEmpty()) {
            System.out.println(" (Your list is currently empty)");
        } else {
            for (int i = 0; i < taskList.size(); i++) {
                System.out.println((i + 1) + ". " + taskList.get(i));
            }
        }
    }

    // enum Code generated by Codex with Qwen3-coder-next with some modifications
    private enum Command {
        LIST,
        MARK,
        DELETE,
        TODO,
        DEADLINE,
        EVENT,
        BYE;

        public static Command fromInput(String input) {
            String lowerInput = input.toLowerCase().trim();
            for (Command cmd : Command.values()) {
                if (cmd.name().toLowerCase().equals(lowerInput)) {
                    return cmd;
                }
                if (lowerInput.startsWith(cmd.name().toLowerCase())) {
                    return cmd;
                }
            }
            return null;
        }

        public String getCommandRest(String input) {
            if (!input.startsWith(this.name().toLowerCase())) {
                return "";
            }
            return input.substring(this.name().length());
        }
    }

    public static void main(String[] args) {
        String line = "____________________________________________________________\n";
        String banner = "      _____                \n"
                + "      |  __ \\  ____   ___ _ \n"
                + "      | |  | |/ __ \\ / __' |\n"
                + "      | |  | | |  | | |__| |\n"
                + "      | |__| | |__| |\\___  |\n"
                + "      |_____/ \\____/ ____/ |\n"
                + "                     \\____/ \n";
        String greeting = "WOOF WOOF How can I help? WOOF";

        System.out.println(banner);
        System.out.println(greeting);
        System.out.println(line);

        Scanner scanner = new Scanner(System.in);
        while (scanner.hasNextLine()) {
            try {
                String input = scanner.nextLine().trim();
                if (input.isEmpty()) {
                    System.out.println("...say something? woof...");
                } else {
                    // Code refactored by Codex with Qwen3-coder-next with heavy modifications
                    Command command = Command.fromInput(input);
                    if (command == null) {
                        throw new DogException("I don't understand what you're saying :(");
                    }

                    String rest = command.getCommandRest(input);

                    switch (command) {
                        case BYE:
                            System.out.println("WOOF Goodbye! WOOF WOOF");
                            scanner.close();
                            return;
                        case LIST:
                            System.out.println("Here are the tasks in your list:");
                            displayTaskList();
                            break;
                        case MARK:
                            // Handle marking a task as done: "mark <index>"
                            // Code generated by Codex with Gemma4 26b
                            try {
                                int index = Integer.parseInt(rest.trim()) - 1;
                                if (index >= 0 && index < taskList.size()) {
                                    Task taskToMark = taskList.get(index);
                                    taskToMark.markAsDone();
                                    System.out.println("WOOF! I've marked this task as done:");
                                    System.out.println(" " + taskToMark);
                                } else {
                                    throw new DogException("Task index out of bounds.");
                                }
                            } catch (NumberFormatException e) {
                                throw new DogException("Please provide a valid task number. (e.g., 'mark 2').");
                            }
                            break;
                        case DELETE:
                            // Handle marking a task as done: "mark <index>"
                            // Code generated by Codex with Gemma4 26b
                            try {
                                int index = Integer.parseInt(rest.trim()) - 1;
                                if (index >= 0 && index < taskList.size()) {
                                    Task deletedTask = taskList.remove(index);
                                    System.out.println("WOOF! I've deleted this task:");
                                    System.out.println(" " + deletedTask);
                                    System.out.println("You have " + taskList.size() + " tasks left in your list! WOOF!");
                                } else {
                                    throw new DogException("Task index out of bounds.");
                                }
                            } catch (NumberFormatException e) {
                                throw new DogException("Please provide a valid task number. (e.g., 'delete 2').");
                            }
                            break;
                        case TODO:
                            // Create new Todo task
                            Task newTodo = Todo.parse(rest);
                            taskList.add(newTodo);
                            System.out.println("WOOF! I've added a new task: \n" + newTodo);
                            break;
                        case DEADLINE:
                            // Create new Deadline task
                            Task newDeadline = Deadline.parse(rest);
                            taskList.add(newDeadline);
                            System.out.println("WOOF! I've added a new task: \n" + newDeadline);
                            break;
                        case EVENT:
                            // Create new Event task
                            Task newEvent = Event.parse(rest);
                            taskList.add(newEvent);
                            System.out.println("WOOF! I've added a new task: \n" + newEvent);
                            break;
                    }
                }
            } catch (DogException e) {
                System.out.println("WOOF WOOF there is something wrong:\n" + e.getMessage());
            } finally {
                System.out.println(line);
            }
        }
    }
}