import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Event extends Task {
    protected String from;
    protected String to;

    public Event(String description, String from, String to) {
        super(description);
        this.from = from;
        this.to = to;
    }

    public Event(String description, String from, String to, boolean isDone) {
        super(description, isDone);
        this.from = from;
        this.to = to;
    }

    @Override
    public String toSaveFormat() {
        return String.format("E | %s | %s | %s | %s", getStatusIcon(), description, from, to);
    }

    public static Event fromSaveFormat(String saveString) {
        String[] parts = saveString.split(" \\| ", 5);
        if (parts.length < 5) return null;

        String statusIcon = parts[1].trim();
        String description = parts[2].trim();
        String from = parts[3].trim();
        String to = parts[4].trim();
        boolean isDone = statusIcon.equals("X");

        return new Event(description, from, to, isDone);
    }

    public static Event parse(String input) throws DogException {
        String BAD_INPUT_MSG = "Event tasks must have a description, a start date, and an end date!\n"
                + "Expected: event <description> /from <start date> /to <end date>";

        // Code generated by Codex with Qwen3-coder-next
        // Pattern: " <description> /from <from> /to <to>"
        Pattern pattern = Pattern.compile("^\\s+(.+?)\\s+/from\\s+(.+?)\\s+/to\\s+(.+?)\\s*$");
        Matcher matcher = pattern.matcher(input);

        if (!matcher.matches()) {
            throw new DogException(BAD_INPUT_MSG);
        }

        String description = matcher.group(1).trim();
        String from = matcher.group(2).trim();
        String to = matcher.group(3).trim();

        if (description.isEmpty() || from.isEmpty() || to.isEmpty()) {
            throw new DogException(BAD_INPUT_MSG);
        }

        return new Event(description, from, to);
    }

    @Override
    public String toString() {
        return "[E]" + super.toString() + " (from: " + this.from + " to: " + this.to + ")";
    }
}
