import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;

public class Storage {
    // Storage code generated by Codex with Qwen3-coder-next with some modifications
    private final String filePath;

    public Storage(String filePath) {
        this.filePath = filePath;
    }

    public ArrayList<Task> load() {
        ArrayList<Task> tasks = new ArrayList<>();
        try {
            File file = new File(filePath);
            if (file.exists()) {
                Scanner scanner = new Scanner(file);
                while (scanner.hasNextLine()) {
                    String line = scanner.nextLine();
                    Task task = parseTask(line);
                    if (task != null) {
                        tasks.add(task);
                    }
                }
                scanner.close();
            }
        } catch (FileNotFoundException e) {
            System.out.println("Error loading tasks: File not found");
        }
        return tasks;
    }

    public void save(ArrayList<Task> tasks) {
        try {
            File file = new File(filePath);
            java.io.FileWriter fileWriter = new java.io.FileWriter(file);
            java.io.BufferedWriter writer = new java.io.BufferedWriter(fileWriter);
            for (Task task : tasks) {
                writer.write(task.toSaveFormat());
                writer.newLine();
            }
            writer.close();
        } catch (java.io.IOException e) {
            System.out.println("Error saving tasks: " + e.getMessage());
        }
    }

    private Task parseTask(String line) {
        try {
            String[] parts = line.split(" \\| ", 2);
            String type = parts[0].trim();

            switch (type) {
                case "T":
                    return Todo.fromSaveFormat(line);
                case "D":
                    return Deadline.fromSaveFormat(line);
                case "E":
                    return Event.fromSaveFormat(line);
                default:
                    return null;
            }
        } catch (Exception e) {
            System.out.println("Error parsing task line: " + line);
            return null;
        }
    }
}