import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Todo extends Task {
    public Todo(String description) {
        super(description);
    }

    public Todo(String description, boolean isDone) {
        super(description, isDone);
    }

    public static Todo parse(String input) throws DogException {
        String BAD_INPUT_MSG = "ToDo tasks must have a description!\nExpected: todo <description>";

        // Code generated by Codex with Qwen3-coder-next
        // Pattern: " <description>"
        Pattern pattern = Pattern.compile("^\\s+(.+?)\\s*$");
        Matcher matcher = pattern.matcher(input);

        if (!matcher.matches()) {
            throw new DogException(BAD_INPUT_MSG);
        }

        String description = matcher.group(1).trim();

        if (description.isEmpty()) {
            throw new DogException(BAD_INPUT_MSG);
        }

        return new Todo(description);
    }

    @Override
    public String toString() {
        return "[T]" + super.toString();
    }
}
