import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Todo extends Task {
    public Todo(String description) {
        super(description);
    }

    public static Todo parse(String input) throws DogException {
        // Code generated by Codex with Qwen3-coder-next
        // Pattern: " <description>"
        Pattern pattern = Pattern.compile("^\\s+(.+?)\\s*$");
        Matcher matcher = pattern.matcher(input);

        if (!matcher.matches()) {
            throw new DogException("ToDo tasks must have a description!\n" +
                    "Expected: todo <description>");
        }

        String description = matcher.group(1).trim();

        if (description.isEmpty()) {
            throw new DogException("ToDo tasks can't have an empty description!");
        }

        return new Todo(description);
    }

    @Override
    public String toString() {
        return "[T]" + super.toString();
    }
}
