import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Todo extends Task {
    public Todo(String description) {
        super(description);
    }

    public static Todo parse(String input) {
        // Code generated by Codex with Qwen3-coder-next
        // Pattern: "<description> /by <by>"
        Pattern pattern = Pattern.compile("^(.+?)\\s*$");
        Matcher matcher = pattern.matcher(input);

        if (!matcher.matches()) {
            throw new IllegalArgumentException("Invalid format. Expected: <description>");
        }

        String description = matcher.group(1).trim();

        if (description.isEmpty()) {
            throw new IllegalArgumentException("Description cannot be empty");
        }

        return new Todo(description);
    }

    @Override
    public String toString() {
        return "[T]" + super.toString();
    }
}
