package storage;

import exceptions.DogException;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;

/**
 * Utility class for handling date parsing and formatting.
 * Accepts dates in yyyy-MM-dd format and displays in MMM dd yyyy format.
 */
public class DateUtils {
    // Code generated by Codex with Qwen3-coder-next
    private static final DateTimeFormatter INPUT_FORMATTER = 
        DateTimeFormatter.ofPattern("yyyy-MM-dd");
    private static final DateTimeFormatter OUTPUT_FORMATTER = 
        DateTimeFormatter.ofPattern("MMM dd yyyy");

    /**
     * Parses a date string in yyyy-MM-dd format to LocalDate.
     * 
     * @param dateStr the date string to parse
     * @return the parsed LocalDate
     * @throws DogException if the date string is invalid
     */
    public static LocalDate parse(String dateStr) throws DogException {
        try {
            return LocalDate.parse(dateStr, INPUT_FORMATTER);
        } catch (DateTimeParseException e) {
            throw new DogException("That doesn't seem like a valid date to me!\n"
                    + "Expected: yyyy-MM-dd (e.g., 2019-10-15)");
        }
    }

    /**
     * Formats a LocalDate to display string in MMM dd yyyy format.
     * 
     * @param date the LocalDate to format
     * @return the formatted date string
     */
    public static String format(LocalDate date) {
        return date.format(OUTPUT_FORMATTER);
    }

    /**
     * Parses a date string and returns it in ISO format (yyyy-MM-dd) for storage.
     * 
     * @param dateStr the input date string (yyyy-MM-dd)
     * @return the date in ISO format for reliable storage
     * @throws DogException if the date string is invalid
     */
    public static String toSaveFormat(String dateStr) throws DogException {
        LocalDate date = parse(dateStr);
        return date.toString(); // ISO format: yyyy-MM-dd
    }
}
